export const DO_LOGIN = "DO_LOGIN";
export const FAIL_LOGIN = "FAIL_LOGIN";
export const DO_REGISTER = "DO_REGISTER";
export const FAIL_REGISTER = "FAIL_REGISTER";
export const LOAD = "LOAD";
export const LOAD_SET_TARGET = "LOAD_SET_TARGET";
export const RESET_PICKER_SET_TARGET = "RESET_PICKER_SET_TARGET";
export const CURRENT_DAY_READING = "CURRENT_DAY_READING"
